### REGISTRO
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
  "nombre": "Yazmin",
  "correo": "yaz@gmail.com",
  "contrasena": "123456"
}

###

### LOGIN
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "correo": "luis@example.com",
  "contrasena": "123456"
}

### 🔐 COPIA EL TOKEN DEL LOGIN Y PÉGALO AQUÍ ABAJO
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2E2N2Y2M2FhMjJmNmVmZGZkYmEwYSIsImlhdCI6MTc0ODY1ODIwNn0.UYueGvCmzbedv4hfruePhP4s5HqOTykCefxJla7ucxI

###

### CREAR TAREA
POST http://localhost:4000/api/tasks
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2E2N2Y2M2FhMjJmNmVmZGZkYmEwYSIsImlhdCI6MTc0ODY1ODIwNn0.UYueGvCmzbedv4hfruePhP4s5HqOTykCefxJla7ucxI
Content-Type: application/json

{
  "descripcion": "Barrer la cocina",
  "categoria": "Cocina"
}

###

### MARCAR TAREA COMO COMPLETADA
PATCH http://localhost:4000/api/tasks/PASTE_TASK_ID_HERE/complete
Authorization: {{token}}

###

### VER TAREAS COMPLETADAS POR CATEGORÍA
GET http://localhost:4000/api/tasks/completadas/Cocina
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4M2E2N2Y2M2FhMjJmNmVmZGZkYmEwYSIsImlhdCI6MTc0ODY1ODIwNn0.UYueGvCmzbedv4hfruePhP4s5HqOTykCefxJla7ucxI

###

### ELIMINAR TAREA
DELETE http://localhost:4000/api/tasks/PASTE_TASK_ID_HERE
Authorization: {{token}}

### Obtener tareas activas
GET http://localhost:4000/api/tasks/pendientes
Authorization: Bearer TU_TOKEN
